[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = {version = "1.0.48", features = ["backtrace"] }
reqwest = {version = "0.11.6", features = ["json"] }
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.72"
serde_yaml = "0.8.21"
